from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate,Paragraph,Spacer,Table,TableStyle,PageBreak
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet,ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.units import mm
out='/mnt/data/restaurant-app-mvp/A1/SRS.pdf'
styles=getSampleStyleSheet(); styles.add(ParagraphStyle(name='CenterTitle',parent=styles['Title'],alignment=TA_CENTER)); styles.add(ParagraphStyle(name='Small',parent=styles['BodyText'],fontSize=8.5,leading=11))
story=[]
def H(t,l=1): story.append(Paragraph(t,styles['Heading%d'%min(l,4)])); story.append(Spacer(1,4))
def P(t): story.append(Paragraph(t,styles['BodyText'])); story.append(Spacer(1,5))
story += [Paragraph('Software Requirements Specification (SRS)',styles['CenterTitle']),Paragraph('Restaurant App MVP — Frontend Only — Fall 2026',styles['CenterTitle']),Spacer(1,12)]
P('This SRS defines the frontend-only Restaurant App MVP. The assignment requires a React Native prototype using React hooks, mock/local data, UML models, customer ordering and reservation flows, and a manager dashboard. The implementation intentionally excludes a backend, external API, real payments, and push notification service.')
H('1. Introduction',1); H('1.1 Purpose',2); P('The purpose is to specify a mobile restaurant experience in which a customer can authenticate, browse a categorized menu, search and sort dishes, manage a cart, apply a promo code, reserve a table, place an order, and watch a simulated order lifecycle. A manager can inspect orders and modify menu availability/prices through the same frontend prototype.')
H('1.2 Scope',2); P('<b>In scope:</b> login/signup, role selection, mock authentication, menu loading, categories, search/debounce, sorting, favourites, cart, promo codes, order summary, reservation form and availability, profile/theme, order tracking, manager order controls, manager menu controls, AsyncStorage persistence, bottom tabs and nested stack navigation, safe-area compatible layouts, and UML/SRS documentation. <b>Out of scope:</b> backend services, remote database, real payment processing, push notifications, production authentication, real-time server order updates, external restaurant APIs, and actual payment settlement.')
H('1.3 Definitions and Acronyms',2)
defs=[['SRS','Software Requirements Specification'],['MVP','Minimum Viable Product'],['UML','Unified Modeling Language'],['Hook','React function used to access state, effects, refs, context or memoization'],['Context','React mechanism for sharing values without prop drilling'],['Reducer','Pure function that calculates the next state from current state and an action'],['Mock Data','Local sample data used instead of a backend'],['FlatList','React Native performant list component'],['AsyncStorage','Local key-value persistence mechanism'],['Promo Code','Local code that applies a percentage discount']]
story.append(Table(defs,colWidths=[35*mm,140*mm],style=[('GRID',(0,0),(-1,-1),.4,colors.grey),('BACKGROUND',(0,0),(0,-1),colors.whitesmoke),('VALIGN',(0,0),(-1,-1),'TOP')]))
H('2. Overall Description',1); H('2.1 User Roles',2); story.append(Table([['Role','Permissions & Goals'],['Customer','Browse/search menu, view specials, manage cart, apply promo, reserve a table, place order, track order, view profile and theme.'],['Manager','Access manager dashboard, review/update order status, inspect reservations, and update menu availability/prices.']],colWidths=[35*mm,140*mm],style=[('GRID',(0,0),(-1,-1),.4,colors.grey),('BACKGROUND',(0,0),(-1,0),colors.lightgrey)])); Spacer(1,8)
H('2.2 User Stories',2)
stories=['As a customer, I want to browse daily specials, so that I can quickly choose a meal.','As a customer, I want to search dishes, so that I can find food without scrolling everything.','As a customer, I want categories, so that I can focus on starters, mains, desserts, or drinks.','As a customer, I want to add notes to cart items, so that I can request changes such as no onions.','As a customer, I want to apply a promo code, so that I can see a discounted total.','As a customer, I want to reserve a table, so that I can arrive with seating arranged.','As a customer, I want to see order progress, so that I know whether my food is pending, preparing, ready, or served.','As a manager, I want to see incoming orders, so that I can update their status.','As a manager, I want to toggle menu availability, so that unavailable dishes are not ordered.','As a manager, I want to adjust a menu price, so that the customer menu reflects current prices.']
for i,x in enumerate(stories,1): P(f'{i}. {x}')
H('3. Functional Requirements',1)
reqs=['The system shall validate login email format and password requirements.','The system shall authenticate against a local mock users array after a simulated one-second delay.','The system shall navigate customers to the menu after successful login.','The system shall navigate managers to the manager dashboard after successful login.','The system shall load at least fifteen menu items across four required categories.','The system shall display category chips and filter menu items by selected category.','The system shall show loading/error/retry states for simulated menu loading.','The system shall allow text search with a 400 ms debounce.','The system shall provide price low-to-high, price high-to-low, and name A-Z sorting.','The system shall disable Add for unavailable menu items.','The system shall add menu items to a cart and maintain quantities.','The system shall support increment, decrement, removal, and special instructions.','The system shall apply WELCOME10 and FEAST20 local promo codes and reject invalid codes.','The system shall calculate subtotal, service charge, tax, discount, and grand total.','The system shall accept Dine-in or Takeaway order type.','The system shall create an order with id, items, total, type, status, and timestamp.','The system shall simulate Pending, Preparing, Ready, and Served order progression.','The system shall validate reservation date, party size, phone format, time and table selection.','The system shall show table choices according to party size.','The system shall expose profile information and a light/dark theme toggle.','The system shall restrict the Manager tab to manager-role users.','The system shall allow managers to update order status.','The system shall allow managers to toggle menu availability and edit prices.','The system shall persist orders and menu edits locally using AsyncStorage.']
for i,r in enumerate(reqs,1): P(f'<b>FR-{i:02d}:</b> {r}')
H('4. Non-Functional Requirements',1); P('<b>Usability:</b> primary actions use readable labels, clear feedback, disabled states and friendly empty/error messages. <b>Performance:</b> menu uses FlatList; search is debounced; derived lists/totals use useMemo; memoized cards and useCallback reduce avoidable child renders. <b>Responsiveness:</b> layouts use flexible widths, wrapping chips, scroll views and native components for different phone sizes. <b>Maintainability:</b> screens, components, contexts, reducers, hooks, data, navigation and theme are separated under src. <b>Data handling:</b> all application data is mock/local; AsyncStorage persists selected prototype data; there is no backend dependency.')
H('5. Client-Side Data Model',1); data=[['Data Set','Important Fields'],['Users','id, name, email, password, role'],['Categories','name / category label'],['MenuItems','id, name, description, price, category, image, isSpecial, isAvailable'],['Tables','id, number, seats'],['Reservations','id, date, time, partySize, table, contact, status'],['Orders','id, items, total, type, status, timestamp, customerId']]; story.append(Table(data,colWidths=[40*mm,135*mm],style=[('GRID',(0,0),(-1,-1),.4,colors.grey),('BACKGROUND',(0,0),(-1,0),colors.lightgrey)])); Spacer(1,8)
H('6. UML Diagrams',1); P('The A1/UML folder contains the five requested diagrams: Use Case, Class, Sequence, State Machine, and Component. Each diagram is accompanied by its PlantUML source so it can be regenerated or edited. The models connect Customer/Manager actors to menu, cart, reservation, order, and React Native architecture concepts.')
H('7. MVP Frontend Development',1)
for title,p in [('7.1 Login and Signup Screen','Uses useState for mode, controlled inputs, validation errors, password visibility and submitting state. Entry is the unauthenticated root; successful customer login enters Main, while manager login exposes Manager.'),('7.2 Menu Browsing Screen','Uses useEffect/useMemo/useCallback and local menu data. Displays categories, specials, availability, sorting and a FlatList.'),('7.3 Search and Scroll Controls','Uses a TextInput ref, debounced query hook, FlatList ref, scroll threshold state, and render counter ref.'),('7.4 Profile and Theme Screen','Uses AuthContext and ThemeContext to show identity, role and instantly switch the application palette.'),('7.5 Cart Screen','Uses CartContext/useReducer for item quantities, notes, removal and promo actions.'),('7.6 Order Summary Screen','Uses useMemo for subtotal, service charge, tax, discount and grand total, then dispatches a new order.'),('7.7 Table Reservation Screen','Uses useReservation for date, time, party size, table and contact logic; UI displays hourly slots and suitable tables.'),('7.8 Order Tracking and Manager Dashboard','Uses useEffect timers for demo order progression and AsyncStorage-backed shared order/menu state. Manager-only controls update the same local data used by customer screens.')]: H(title,2); P(p)
H('8. Testing / Demonstration',1); P('Manual flow: sign up/login as customer → browse → search → add items → apply promo → reserve a table → place an order → observe tracking progression → log in as manager → update the same order/menu. The repository README contains credentials and the hook coverage table. Screenshots and a final screen-recording link can be added before submission.')

doc=SimpleDocTemplate(out,pagesize=A4,rightMargin=16*mm,leftMargin=16*mm,topMargin=15*mm,bottomMargin=15*mm);doc.build(story)
print(out)
